export interface TeamMember {
  fullName: string;
  nickname: string;
  dob: string;
  occupation: string;
  favoriteColor: string;
  instagram: string;
  photo: string;
}

export const teamMembers: TeamMember[] = [
  {
    fullName: "Fadahunsi Oluwabusayo",
    nickname: "Minister B",
    dob: "Nov-25",
    occupation: "Graphic Designer",
    favoriteColor: "#000000",
    instagram: "ministerbusayo_official",
    photo: "https://drive.google.com/open?id=11ZsDjkMjoz6hXxzIUg_gR70_n_vu0JWr",
  },
  {
    fullName: "Olayinka Deborah",
    nickname: "Horlaryeenkhar💕",
    dob: "Nov-01",
    occupation: "Employee",
    favoriteColor: "#FFC0CB",
    instagram: "Horlaryeenkhar",
    photo: "https://drive.google.com/open?id=1WTNjTHfGdofR2ZTJnISC_EDpV_ooA_86",
  },
  {
    fullName: "Olamilekan Agbaje",
    nickname: "Agbaje",
    dob: "20-Apr",
    occupation: "Searching",
    favoriteColor: "#0000FF",
    instagram: "Agbaje Olamilekan",
    photo: "https://drive.google.com/open?id=19bS90bZSfwT1OSvezn8hPGB7C-13tmAl",
  },
  {
    fullName: "Promise victory osai",
    nickname: "Ojere",
    dob: "31-Jul",
    occupation: "Makeup artist/ engineer",
    favoriteColor: "#000000",
    instagram: "IG : Barbieojere Snapchat: Barbieojere123",
    photo: "https://drive.google.com/open?id=12QlMmnAyl6j0BW_m5P_ih5IW5S0jtQg_",
  },
  {
    fullName: "Ayomide Praise",
    nickname: "Mama",
    dob: "4/5/2025",
    occupation: "Nill",
    favoriteColor: "#800080",
    instagram: "@bigmama2716",
    photo: "https://drive.google.com/open?id=1Yns5fB7N5zMZyNLiiX8VKrMIpLYU40yg",
  },
  {
    fullName: "Alabi simbiat ovayorza",
    nickname: "Ovy",
    dob: "8-Oct-25",
    occupation: "Fashion designer",
    favoriteColor: "#FFFFFF",
    instagram: "@ alabi simbiat ovayorza",
    photo: "https://drive.google.com/open?id=18lDPBJdbAnS4dOa4e3bTJRPfcBZxHqx3",
  },
  {
    fullName: "Amos Isaac Olaoluwa",
    nickname: "Neo",
    dob: "February 18th",
    occupation: "Accountant",
    favoriteColor: "#B2BEB5",
    instagram: "real_ne00 (instagram)",
    photo: "https://drive.google.com/open?id=1llOeYfFkLGCDavvdvIbr2YRTdnB94gYO",
  },
  {
    fullName: "Ngadi Favour .C.",
    nickname: "Faverite08",
    dob: "Nov-08",
    occupation: "Sales manager",
    favoriteColor: "#000000",
    instagram: "NGADI FAVOUR CHIDINMA (Instagram)",
    photo: "https://drive.google.com/open?id=13rm8yWCziXB3zvr3mQejQivzHbsepiAx",
  },
  {
    fullName: "Akintola Omowunmi Olaitan",
    nickname: "Akint",
    dob: "25-Jul",
    occupation: "Designer",
    favoriteColor: "#FFFFFF",
    instagram: "Tt @mhizakint. Ig @mhizakint_",
    photo: "https://drive.google.com/open?id=11KoPYZi0UnidazlrNDlsZArhYPZpQJvt",
  },
  {
    fullName: "Miracle Abiodun",
    nickname: "Miraywonder",
    dob: "4/25/2025",
    occupation: "Fashion Designer/ Health Nutritionist.",
    favoriteColor: "#FFFFFF",
    instagram: "Instagram: @mir_ay113, Twitter: @Miray1485149",
    photo: "https://drive.google.com/open?id=11Fito5kxqrpNItXVlbtBglsgAe903SKA",
  },
  {
    fullName: "Babalola Ayomide Olamide",
    nickname: "Ayo",
    dob: "5/12/2025",
    occupation: "Corper",
    favoriteColor: "#D3D3D3",
    instagram: "@beaut_3080",
    photo: "https://drive.google.com/open?id=1QE-vbVuB9YpuNjbSsAL3uA5h4QUT0v2R",
  },
  {
    fullName: "Oluwafemi Omolounnu",
    nickname: "The Priestly TechBro",
    dob: "19th August",
    occupation: "Software Engineer",
    favoriteColor: "#0000FF",
    instagram: "the_priestly_techbro",
    photo: "https://drive.google.com/open?id=11X51yt2GToTQCi1D3I5Po9e3nImAjZtN",
  },
  {
    fullName: "Jimoh Aramide",
    nickname: "Aramide",
    dob: "10-Mar",
    occupation: "Hair stylist",
    favoriteColor: "#0000FF,#000000",
    instagram: "Mide_luxe_braids",
    photo: "https://drive.google.com/open?id=1cHcRlM31Xtt_flHwKF57jnBmJ4tAkiJx",
  },
  {
    fullName: "Ola Oyinkonsola",
    nickname: "Honeydrop",
    dob: "13-Jul-04",
    occupation: "Makeup artist",
    favoriteColor: "#800080",
    instagram: "@Honeydrop058",
    photo: "https://drive.google.com/open?id=1EIO46wkHXOwiG6HPDMbGeU8bOqDir_Ya",
  },
  {
    fullName: "Olamilekan Adewale Agbaje",
    nickname: "Ola",
    dob: "20-Apr-95",
    occupation: "Customer service",
    favoriteColor: "#0000FF",
    instagram: "https://www.facebook.com/share/17Qb4zhpfK/",
    photo: "https://drive.google.com/open?id=1r2ViEs8oCV2SJZQ1rJE8fSN-U8hW2RJI",
  },
  {
    fullName: "Akintola Omowunmi",
    nickname: "Akint",
    dob: "25-Jul",
    occupation: "Fashion designer",
    favoriteColor: "#FFFFFF",
    instagram: "Mhiz_akint",
    photo: "https://drive.google.com/open?id=1IpABiwagxMzhwH1uTtwBHYqyi4VoObvG",
  },
  {
    fullName: "Falade Johnson Daramola",
    nickname: "Jay Johnson",
    dob: "7-May",
    occupation: "Fashion Designer",
    favoriteColor: "#87CEEB",
    instagram: "Jay Johnson Outfits",
    photo: "https://drive.google.com/open?id=1Y_kpkrUOrWPhptKSiTwaM7-S32d7nJ8A",
  },
  {
    fullName: "Akintola Oluwatosin",
    nickname: "TOSPET",
    dob: "Sept. 05",
    occupation: "Engineer",
    favoriteColor: "#B2BEB5,#808080",
    instagram: "Tospet_akint",
    photo: "https://drive.google.com/open?id=1uDgPawwlb4jF_kRVZ5q9EbNwmAogyvcq",
  },
  {
    fullName: "Oluwasegun Kayode",
    nickname: "kaykay",
    dob: "August 5th",
    occupation: "Software Engineer",
    favoriteColor: "#000000",
    instagram: "olaolu_kayode",
    photo: "https://drive.google.com/open?id=1iUpA6NJrHoeic_tjhwzBE5a_ttHnXFh_",
  },
  {
    fullName: "Fariogun Folakemi",
    nickname: "Greatmuse",
    dob: "24th November",
    occupation: "French tutor",
    favoriteColor: "#800080",
    instagram: "fola_greatmuse",
    photo: "https://drive.google.com/open?id=1xKaGfN6K3jOmZopkVHTjcLflPdreUzK8",
  },
  {
    fullName: "Oluwadahunsi Adeyinka",
    nickname: "Oluwadahunsi",
    dob: "22-Oct",
    occupation: "Consultant",
    favoriteColor: "#D3D3D3",
    instagram: "@a_dahunsi",
    photo: "https://drive.google.com/open?id=1V_naSebjOPub1CwDCN-EPCzQEUCNyqpO",
  },
  {
    fullName: "Fawunmi temitope oladipupo",
    nickname: "Topteezee",
    dob: "6/25/1995",
    occupation: "Businessman",
    favoriteColor: "#000000",
    instagram: "Topteezee55",
    photo: "https://drive.google.com/open?id=1JKgannJ3ApJz-mzXnfS5tr4_CI0Q--IP",
  },
  {
    fullName: "Oyelakin Deborah Ayonimofe",
    nickname: "Babydebo",
    dob: "May 16th 2003",
    occupation: "Employee & Clothing Vendor (Unisex)",
    favoriteColor: "#0000FF,#FFC0CB",
    instagram: "@babydebo35",
    photo: "https://drive.google.com/open?id=1jhFZLdUaXCxT-Y-b8yEFUqLK7Kmi8lTb",
  },
  {
    fullName: "Ibrahim Mary omotolani",
    nickname: "Lannie",
    dob: "7-Sep",
    occupation: "Fashion designer",
    favoriteColor: "#7B3F00",
    instagram: "Oluwayemisi",
    photo: "https://drive.google.com/open?id=1Udj_W_TT9tcHW0U8SeaKpWB3XZg9IRi6",
  },
];
