export interface TeamMember {
  fullName: string;
  nickname: string;
  dob: string;
  occupation: string;
  favoriteColor: string;
  instagram: string;
  photo: string;
}

export const teamMembers: TeamMember[] = [
  {
    fullName: "Fadahunsi Oluwabusayo",
    nickname: "Minister B",
    dob: "Nov-25",
    occupation: "Graphic Designer",
    favoriteColor: "#000000",
    instagram: "ministerbusayo_official",
    photo: "/people/fadahunsi.jpg",
  },
  {
    fullName: "Olayinka Deborah",
    nickname: "Horlaryeenkhar💕",
    dob: "Nov-01",
    occupation: "Employee",
    favoriteColor: "#FFC0CB",
    instagram: "Horlaryeenkhar",
    photo: "/people/yinka.jpeg",
  },
  {
    fullName: "Olamilekan Adewale Agbaje",
    nickname: "Ola",
    dob: "20-Apr",
    occupation: "Customer service",
    favoriteColor: "#0000FF",
    instagram: "https://www.facebook.com/share/17Qb4zhpfK/",
    photo: "/people/lekan.jpg",
  },
  {
    fullName: "Promise victory osai",
    nickname: "Ojere",
    dob: "31-Jul",
    occupation: "Makeup artist/ engineer",
    favoriteColor: "#000000",
    instagram: "IG : Barbieojere Snapchat: Barbieojere123",
    photo: "/people/promise.jpeg",
  },
  {
    fullName: "Ayomide Praise",
    nickname: "Mama",
    dob: "4/5/2025",
    occupation: "Nill",
    favoriteColor: "#800080",
    instagram: "@bigmama2716",
    photo: "/people/ayomide-esther.jpeg",
  },
  {
    fullName: "Alabi simbiat ovayorza",
    nickname: "Ovy",
    dob: "8-Oct-25",
    occupation: "Fashion designer",
    favoriteColor: "#FFFFFF",
    instagram: "@ alabi simbiat ovayorza",
    photo: "/people/alabi.jpeg",
  },
  {
    fullName: "Amos Isaac Olaoluwa",
    nickname: "Neo",
    dob: "February 18th",
    occupation: "Accountant",
    favoriteColor: "#B2BEB5",
    instagram: "real_ne00 (instagram)",
    photo: "/people/isaac.jpg",
  },
  {
    fullName: "Ngadi Favour .C.",
    nickname: "Faverite08",
    dob: "Nov-08",
    occupation: "Sales manager",
    favoriteColor: "#000000",
    instagram: "NGADI FAVOUR CHIDINMA (Instagram)",
    photo: "/people/favour.jpeg",
  },
  {
    fullName: "Akintola Omowunmi Olaitan",
    nickname: "Akint",
    dob: "25-Jul",
    occupation: "Designer",
    favoriteColor: "#FFFFFF",
    instagram: "Tt @mhizakint. Ig @mhizakint_",
    photo: "/people/omowunmi.jpeg",
  },
  {
    fullName: "Miracle Abiodun",
    nickname: "Miraywonder",
    dob: "4/25/2025",
    occupation: "Fashion Designer/ Health Nutritionist.",
    favoriteColor: "#FFFFFF",
    instagram: "Instagram: @mir_ay113, Twitter: @Miray1485149",
    photo: "/people/miracle.jpg",
  },
  {
    fullName: "Babalola Ayomide Olamide",
    nickname: "Ayo",
    dob: "5/12/2025",
    occupation: "Corper",
    favoriteColor: "#D3D3D3",
    instagram: "@beaut_3080",
    photo: "/people/ayomide-babalola.jpeg",
  },
  {
    fullName: "Oluwafemi Omolounnu",
    nickname: "The Priestly TechBro",
    dob: "19th August",
    occupation: "Software Engineer",
    favoriteColor: "#0000FF",
    instagram: "the_priestly_techbro",
    photo: "/people/omolounnu.jpg.jpg",
  },
  {
    fullName: "Jimoh Aramide",
    nickname: "Aramide",
    dob: "10-Mar",
    occupation: "Hair stylist",
    favoriteColor: "#0000FF,#000000",
    instagram: "Mide_luxe_braids",
    photo: "/people/aramide.jpeg",
  },
  {
    fullName: "Ola Oyinkonsola",
    nickname: "Honeydrop",
    dob: "13-Jul-04",
    occupation: "Makeup artist",
    favoriteColor: "#800080",
    instagram: "@Honeydrop058",
    photo: "/people/ola.jpeg",
  },
  {
    fullName: "Akintola Omowunmi",
    nickname: "Akint",
    dob: "25-Jul",
    occupation: "Fashion designer",
    favoriteColor: "#FFFFFF",
    instagram: "Mhiz_akint",
    photo: "/people/wunmi.jpeg",
  },
  {
    fullName: "Falade Johnson Daramola",
    nickname: "Jay Johnson",
    dob: "7-May",
    occupation: "Fashion Designer",
    favoriteColor: "#87CEEB",
    instagram: "Jay Johnson Outfits",
    photo: "/people/falade.jpg",
  },
  {
    fullName: "Akintola Oluwatosin",
    nickname: "TOSPET",
    dob: "Sept. 05",
    occupation: "Engineer",
    favoriteColor: "#B2BEB5,#808080",
    instagram: "Tospet_akint",
    photo: "/", // TODO
  },
  {
    fullName: "Oluwasegun Kayode",
    nickname: "kaykay",
    dob: "August 5th",
    occupation: "Software Engineer",
    favoriteColor: "#000000",
    instagram: "olaolu_kayode",
    photo: "/people/kayode.jpg",
  },
  {
    fullName: "Fariogun Folakemi",
    nickname: "Greatmuse",
    dob: "24th November",
    occupation: "French tutor",
    favoriteColor: "#800080",
    instagram: "fola_greatmuse",
    photo: "/people/folakemi.JPG",
  },
  {
    fullName: "Oluwadahunsi Adeyinka",
    nickname: "Oluwadahunsi",
    dob: "22-Oct",
    occupation: "Consultant",
    favoriteColor: "#D3D3D3",
    instagram: "@a_dahunsi",
    photo: "/people/adeyinka.jpg",
  },
  {
    fullName: "Fawunmi temitope oladipupo",
    nickname: "Topteezee",
    dob: "6/25",
    occupation: "Businessman",
    favoriteColor: "#000000",
    instagram: "Topteezee55",
    photo: "/people/temitope.jpg",
  },
  {
    fullName: "Oyelakin Deborah Ayonimofe",
    nickname: "Babydebo",
    dob: "May 16th 2003",
    occupation: "Employee & Clothing Vendor (Unisex)",
    favoriteColor: "#0000FF,#FFC0CB",
    instagram: "@babydebo35",
    photo: "/people/deborah.jpg",
  },
  {
    fullName: "Ibrahim Mary omotolani",
    nickname: "Lannie",
    dob: "7-Sep",
    occupation: "Fashion designer",
    favoriteColor: "#7B3F00",
    instagram: "Oluwayemisi",
    photo: "/people/blessing.jpg",
  },
];
